name: Clean Up (Destroy)

on:
  workflow_dispatch: # Chỉ chạy khi bạn nhấn nút thủ công trên GitHub

permissions:
  contents: read

env:
  TF_DIR: .github/terraform

jobs:
  terraform-destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-southeast-1
      TERRAFORM_VARS: ${{ secrets.TERRAFORM_VARIABLES }}

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85
        with:
          terraform_version: "1.14.6"

      - name: Write terraform.tfvars from secret
        working-directory: ${{ env.TF_DIR }}
        run: printf "%s\n" "$TERRAFORM_VARS" > terraform.tfvars

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Terraform Init
        working-directory: ${{ env.TF_DIR }}
        run: terraform init

      - name: Terraform Destroy
        working-directory: ${{ env.TF_DIR }}
        run: terraform destroy -auto-approve
